---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageDigestMirrorSet
metadata:
  name: example-mirror-set
spec:
  imageDigestMirrors:
    - mirrors:
        - brew.registry.redhat.io/container-native-virtualization
      source: registry.redhat.io/container-native-virtualization